config/routes.rb
Rails.application.routes.draw do

    resources :songs do
      resources :surveys
    end
    resources :artists
    resources :users
    resources :sessions

    get "/login", to: "sessions#new"
    get "/logout", to: "sessions#destroy"
    
    root to: 'songs#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :song
  belongs_to :survey
  has_many :answers
  #has_many :questions, dependent: :destroy
  #has_many :songs, through: :questions
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_many :surveys 
  #has_many :questions
  #has_many :surveys, through: :questions

  validates :name, presence: :true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :song
  belongs_to :user
  #has_many :questions, dependent: :destroy
  #has_many :songs, through: :questions
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

#  def index
 #   @survey = Survey.all
#  end

  def show
    @survey = Survey.find_by(id: params["id"])
    @questions = @survey.questions
  end

  def new
    @survey = survey.find_by(id: params["survey_id"])
    @answer = Answer.new
  end

  def show
    @answer = answer.find_by(id: params["answer_id"])
  end

  def create
    @survey = survey.find_by(id: params["survey_id"])
    answer_params = params.require(:answer).permit!
    @answer = @survey.answer.new(answer_params)
    @answer.user = current_user
    if @answer.save
      redirect_to @song, notice: "Thanks for answering the survey!"
    else
      render "new"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :require_user

  def current_user
    User.find_by(id: session["user_id"])
  end

  def require_user
    if current_user.nil?
      redirect_to new_session_path
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController <ApplicationController

  def index
    @artists = Artist.all    
  end

  def show
    @artist = Artist.find_by(id: params["id"])
  end

  def new
    @artist = Artist.new
  end

  def create
    artist_params = params.require(:artist).permit!
      @artist = Artist.create(artist_params)
    if @artist.valid?
      redirect_to artists_path
    else
      render text: "FAIL"
    end
  end

  def edit
    @artist = Artist.find_by(id: params["id"])
  end

  def update
    artist_params = params.require(:artist).permit!
    @artist = Artist.find_by(id: params["id"])
    @artist.update(artist_params)
    redirect_to artists_path
  end

  def destroy
    @artist = Artist.find_by(id: params["id"])
    @artist.destroy
    redirect_to artists_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false
  skip_before_action :require_user

  def create
    # params["email"] => the email address
    # params["password"] => the password
    # Do authentication
    # Redirect to the root_path
    # Display a notice that login was either successful or unsuccessful

    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to root_path, notice: "Welcome to Tempo!"
    else
      redirect_to root_path, alert: "Please try logging in again."
    end

  end

  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "Thanks for using Tempo!"
  end

end

app/controllers/songs_controller.rb
class SongsController <ApplicationController

  def index
    @songs = Song.all    
  end

  def show
    @song = Song.find_by(id: params["id"])
  end

#  def new
 #   @song = Song.new
#  end

#  def create
 #   song_params = params.require(:song).permit!
  #    @song = Song.create(song_params)
   # if @song.valid?
    #  redirect_to songs_path
    #else
     # render text: "FAIL"
   # end
#  end

#  def edit
 #   @song = Song.find_by(id: params["id"])
#  end

#  def update
 #   song_params = params.require(:song).permit!
  #  @song = Song.find_by(id: params["id"])
   # @song.update(song_params)
    #redirect_to songs_path
#  end

#  def destroy
 #   @song = Song.find_by(id: params["id"])
  #  @song.destroy
   # redirect_to songs_path
 # end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :find_song

  def new
    @survey = Survey.new
  end

  def create
    survey_params = params.require(:survey).permit(:rating)
    @survey = @song.surveys.new(survey_params)
    @survey.user = current_user
    if @survey.save
      redirect_to @song, notice: "Thanks for answering the survey!"
    else
      render "new"
    end
  end

  def find_song
    @song = Song.find_by(id: params["song_id"])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params["id"])
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit!
    @user = User.create(user_params)
    if @user.valid?
      redirect_to users_path, notice: "Sweet"
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params["id"])
  end

  def update
    user_params = params.require(:user).permit!
    @user = User.find_by(id: params["id"])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find_by(id: params["id"])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<table class="table">
<% @artists = Artist.all %>

<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">

        <div class="caption">
          <h3><%= link_to artist.name, artist %></h3>

        </div>
      </div>
    </div>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tempo</title>
    <!-- Logo Font -->
    <link href="http://fonts.googleapis.com/css?family=Arimo:700italic" rel="stylesheet" type="text/css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">

      <!-- Alerts -->
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      
      <nav class="navbar navbar-inverse" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Rails equivalent to -->
          <!-- <a href="/" class="navbar-brand">Tempo</a> -->
          <%= link_to "Tempo", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="/">
                <i class="fa fa-home"></i>
                Home
              </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-cog"></i>
                Admin
                <span class="caret"></span>
              </a>
            <ul class="dropdown-menu" role="menu">
              <li><%=link_to "Songs", songs_path %></li>
              <li><%=link_to "Artists", artists_path %></li>
              <li><%=link_to "Users", users_path %></li>
          </ul>
            <li>
              <% if current_user %>
                <a href="#">
                  <i class="fa fa-user"></i>
                  Hi, <%= current_user.try(:name) %>
                </a>
              <% else %>
                <%= link_to "Log In", login_path %>
              <% end %>
            </li>
            <li>
              <% if current_user %>
                <%= link_to "Log Out", logout_path %>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/index.html.erb
<table class="table">
<% @songs = Song.all %>

<div class="jumbotron">
  <br><br><br><br><br>
    <h1>tempo</h1>
</div>

<div class="row">
  <% @songs.each do |song| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">

        <div class="caption">
          <h3><%= link_to song.name, song %></h3>
          <p><%= song.artist.name %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/songs/new.html.erb
<h1>Enter a New Song</h1>

<%= form_for @song do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :year_released %>
    <%= form.text_field :year_released, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :artist_id %>
    <%= form.collection_select :artist_id, Artist.order(:name), :id, :name, { include_blank: true }, { class: "form-control" } %>
  </div>

  <%= form.button 'Create Song', class: "btn btn-success" %>
<% end %>

app/views/songs/show.html.erb
<h1>Song Detail</h1>

<p>Title: <%= @song.name %></p>

<p>Year Released: <%= @song.year_released %></p>

<p>Artist: <%= @song.artist.name %></p>

<h3><%= link_to "Take a quick Survey", new_song_survey_path(@song) %></h3>

app/views/surveys/new.html.erb
<h1>Take a Survey</h1>

<%= form_for [@song, @survey] do |form| %>
  <div class="form-group">
    <%= form.label :How_Would_You_Describe_the_Artists_Voice? %>
    <%= form.select :rating, ["Good", "Bad"], class: "form-control" %>
  </div>
  <%= form.button 'Post Your Feedback', class: "btn btn-success" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <%= form.button 'Update', class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<h3 class="page-header">
  All Users
  <span class="pull-right">
    <%= link_to "New User", new_user_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> <%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <%= form.button 'Sign Up', class: "btn btn-success" %>
<% end %>